import 'package:json_annotation/json_annotation.dart';

part 'search_bank.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class BankData {
  int? count;
  List<Bank>? data;
  String? message;
  List<dynamic>? misc;

  BankData({this.count, this.data, this.message, this.misc});

  factory BankData.fromJson(Map<String, dynamic> json) => _$BankDataFromJson(json);

  Map<String, dynamic> toJson() => _$BankDataToJson(this);
}

@JsonSerializable()
class Bank {
  int? id;
  String? name;

  Bank({this.id, this.name});

  factory Bank.fromJson(Map<String, dynamic> json) => _$BankFromJson(json);

  Map<String, dynamic> toJson() => _$BankToJson(this);
}
