import 'package:json_annotation/json_annotation.dart';

part 'search_qualification.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class SearchQualification {
  int? status;
  int? count;
  String? message;
  List<QualificationData>? data;

  SearchQualification({this.status, this.count, this.message, this.data});

  factory SearchQualification.fromJson(Map<String, dynamic> json) =>
      _$SearchQualificationFromJson(json);

  Map<String, dynamic> toJson() => _$SearchQualificationToJson(this);
}

@JsonSerializable()
class QualificationData {
  int? id;
  String? name;
  bool? status;
  dynamic deleted_at; // This can be DateTime if it represents a date

  QualificationData({this.id, this.name, this.status, this.deleted_at});

  factory QualificationData.fromJson(Map<String, dynamic> json) =>
      _$QualificationDataFromJson(json);

  Map<String, dynamic> toJson() => _$QualificationDataToJson(this);
}
