// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJy57EcqvMbXRRICzDH6mQuYguve601s',
    appId: '1:322567249626:web:63c01b0ba19c8c10c74fe3',
    messagingSenderId: '322567249626',
    projectId: 'pankaj-trust',
    authDomain: 'pankaj-trust.firebaseapp.com',
    storageBucket: 'pankaj-trust.appspot.com',
    measurementId: 'G-HEMXK40Q47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb1P58mnoUFjHX36ld0qzCNG-eMWJOVn0',
    appId: '1:322567249626:android:0fa64ba786c81999c74fe3',
    messagingSenderId: '322567249626',
    projectId: 'pankaj-trust',
    storageBucket: 'pankaj-trust.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0f9VFN53u2cRZs1Coflr-WaadH_ebV4',
    appId: '1:322567249626:ios:a054fdadfe1a734ac74fe3',
    messagingSenderId: '322567249626',
    projectId: 'pankaj-trust',
    storageBucket: 'pankaj-trust.appspot.com',
    iosBundleId: 'com.example.pankajCloudfirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0f9VFN53u2cRZs1Coflr-WaadH_ebV4',
    appId: '1:322567249626:ios:d66d58d1e7878d56c74fe3',
    messagingSenderId: '322567249626',
    projectId: 'pankaj-trust',
    storageBucket: 'pankaj-trust.appspot.com',
    iosBundleId: 'com.example.pankajCloudfirestore.RunnerTests',
  );
}
