

import 'package:freezed_annotation/freezed_annotation.dart';

part 'school.freezed.dart';
part 'school.g.dart'; // This will be generated by the build_runner

@freezed
class School with _$School {
  const factory School({
    required int id,
    required String name,
    @JsonKey(name: 'created_at') required dynamic createdAt,
  }) = _School;

  factory School.fromJson(Map<String, dynamic> json) => _$SchoolFromJson(json);
}
